### ISSUE TITLE
Custom Emoji translation into all languages

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/RitaBot#117]
**Describe the bug**
Discord uses emojis in the format of :??: when this is translated in to other languages it will work fine. However when translated to CN it will translate to : ?? : 

**Expected behavior**
Translate with no space in : ?? : 

**Additional context**
Issue in all versions of bot.

**Comment by ArtanisTheOne** [comment]
Custom emojis fixed.   Non-latin / non-slavic languages are currently not supported with custom emojis.
