### ISSUE TITLE
Bot to Bot Translation 

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/RitaBot#123]
**Is your feature request related to a problem? Please describe.**
Be able to translate other bot messages, By default, RITA will ignore all messages by bots

**Describe the solution you'd like**
Create a new Role that the bot identifies that simply makes RITA treat the whitelisted bot as regular users.

**Comment by ArtanisTheOne** [comment]
Can make the embed version listen to bots but not itself by doing:

```
if (message.author.id === client.user.id) 
{
return
}
```

and replace:
```
if (message.author.bot)
{
return
}
```
in message.js

**Comment by ZyC0R3** [comment]
Feature Added on Test Branch
