### ISSUE TITLE
Build Fixes Needed

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/RitaBot#139]
**Details from deployment log**
src/core/send.js
- [x] 263:34  warning  Missing semicolon                        semi
- [x] 264:8   warning  Unnecessary semicolon                    no-extra-semi
- [x] 266:4   warning  Block must not be padded by blank lines  padded-blocks
- [x] 338:1   warning  Trailing spaces not allowed              no-trailing-spaces
- [x] 546:1   warning  Trailing spaces not allowed              no-trailing-spaces
- [x] 547:4   warning  Block must not be padded by blank lines  padded-blocks
- [x] 549:1   warning  Block must not be padded by blank lines  padded-blocks
- [x] 549:2   warning  Missing semicolon                        semi

**Comment by ArtanisTheOne** [comment]
Fixed
