### ISSUE TITLE
Reaction Name Bug

### ISSUE THREAD

**Issue by ArtanisTheOne** [ZyC0R3/RitaBot#185]
**Describe the bug**
Nicknames causing huge bugs with reaction translation.  Wrong name, nickname etc;

**To Reproduce**
Turn embed **off**
React on a new message
Then have someone else speak
then react again with different language flag to same message

**Expected behaviour**
To use the correct name and username lol

**Error Message from Webhook**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/52015929/95004351-0ae78b00-05b8-11eb-9abf-d79a1dfa1895.png)

**Comment by ZyC0R3** [comment]
Moved in to 1.2.2 as not impacting issue.

**Comment by ArtanisTheOne** [comment]
Fixed due to nickname removal. Currently not relevant.
