### ISSUE TITLE
Can you write a code for telegram translate bot ?

### ISSUE THREAD

**Issue by telegrambotdev** [ZyC0R3/RitaBot#262]
Can you write a code for telegram translate bot ?

**Comment by ArtanisTheOne** [comment]
How do you mean? @telegrambotdev

**Comment by telegrambotdev** [comment]
> How do you mean? @telegrambotdev

this is code is for discord translation bot right ?
we want a code telegram translation bot.telegram is now the top downloading im in the worldwide,so please make telegram translation bot code


thank you

**Comment by ArtanisTheOne** [comment]
Right now we arent really looking to expand past Discord. I see using a telegram javascript library you could use [google-translate-api](https://github.com/vitalets/google-translate-api) to make your own. I dont know Telegram at all, never heard of it to be honest but you should be able to develop your own with the Internet and guides 🙂

**Comment by telegrambotdev** [comment]
Thank you

**Comment by ArtanisTheOne** [comment]
We will defenitely look into it though and if I can find some spare time I could most likely make a Telegram Bot. But I am a complete noob with the Telegram library
